#!/usr/bin/env python3
"""Inline an SVG's <style> rules as attributes and flatten nested <svg>s,
so react-native-svg's SvgXml (no CSS, no nested viewBox) draws it as a browser does."""
import re, sys, xml.etree.ElementTree as ET
NS = 'http://www.w3.org/2000/svg'
ET.register_namespace('', NS)

def rules(css):
    out = []
    for sel, body in re.findall(r'([^{}]+)\{([^}]*)\}', css):
        props = [tuple(x.strip() for x in d.split(':', 1)) for d in body.split(';') if ':' in d]
        for s in sel.split(','):
            out.append((s.strip(), props))
    return out

def matches(sel, el):
    tag = el.tag.split('}')[1]
    if sel.startswith('.'):
        return sel[1:] in (el.get('class') or '').split()
    return sel == tag

def convert(path):
    root = ET.parse(path).getroot()
    css = ''
    for st in root.iter(f'{{{NS}}}style'):
        css += st.text or ''
    rs = rules(css)
    # Element selectors first (lower specificity), then classes, in source order.
    ordered = [r for r in rs if not r[0].startswith('.')] + [r for r in rs if r[0].startswith('.')]
    for el in root.iter():
        for sel, props in ordered:
            if matches(sel, el):
                for k, v in props:
                    if k in ('font-family', 'font-weight', 'font-size') and el.tag.split('}')[1] != 'text':
                        continue
                    el.set(k, v)
        el.attrib.pop('class', None)
        el.attrib.pop('id', None)
    for parent in root.iter():
        for i, ch in enumerate(list(parent)):
            # <metadata> is the file's provenance record (a C2PA manifest), kept
            # in the .svg as delivered; it draws nothing, so the app goes without.
            if ch.tag in (f'{{{NS}}}defs', f'{{{NS}}}metadata'):
                parent.remove(ch)
            elif ch.tag == f'{{{NS}}}svg':
                x, y = float(ch.get('x', 0)), float(ch.get('y', 0))
                vx, vy, vw, vh = map(float, ch.get('viewBox').split())
                sx, sy = float(ch.get('width')) / vw, float(ch.get('height')) / vh
                s = min(sx, sy)  # preserveAspectRatio xMidYMid meet
                ox = x + (float(ch.get('width')) - vw * s) / 2 - vx * s
                oy = y + (float(ch.get('height')) - vh * s) / 2 - vy * s
                g = ET.Element(f'{{{NS}}}g', {'transform': f'matrix({s:.5f} 0 0 {s:.5f} {ox:.3f} {oy:.3f})'})
                g.extend(list(ch))
                parent.remove(ch)
                parent.insert(i, g)
    xml = ET.tostring(root, encoding='unicode')
    return re.sub(r'>\s+<', '><', xml)

if __name__ == '__main__':
    # python3 scripts/inline-svg.py — every assets/illustrations/*.svg becomes
    # src/illustrations/drawn/<name>.ts, a string for SvgXml. Edit the .svg
    # (the artist's file, as delivered) and run this again; never the .ts.
    import glob, os
    for src in sorted(glob.glob('assets/illustrations/*.svg')):
        name = os.path.splitext(os.path.basename(src))[0]
        xml = convert(src)
        with open(f'src/illustrations/drawn/{name}.ts', 'w') as f:
            f.write(f'// Generated by scripts/inline-svg.py from assets/illustrations/{name}.svg — do not edit.\n')
            assert '`' not in xml and '${' not in xml
            f.write('export default `' + xml + '`;\n')
        print(src, '->', f'src/illustrations/drawn/{name}.ts', len(xml))
